stages:

  get_data:
    cmd: python 02a_sklearn_getdata.py
    deps:
    - 02a_sklearn_getdata.py
    outs:
    - ./data/diabetes.csv
    
  process_data:
    cmd: python 02b_sklearn_processdata.py
    deps:
    - 02b_sklearn_processdata.py
    - ./data/diabetes.csv
    outs:
    - ./data/processed_data.csv

  train_model:
    cmd: python 02c_sklearn_MLP.py
    deps:
    - 02c_sklearn_MLP.py
    - ./data/processed_data.csv
    outs:
    - ./images/sklearn_mlp_loss_curve.png
    - ./models/sklearn_neuralnet.pkl
    metrics:
    - ./metrics/metrics.json:
        cache: false
