stages:

  get_data:
    cmd: python 02a_sklearn_getdata.py
    deps:
    - 02a_sklearn_getdata.py
    outs:
    - ./data/diabetes.csv
    
  process_data:
    cmd: python 02b_sklearn_processdata.py
    deps:
    - 02b_sklearn_processdata.py
    - ./data/diabetes.csv
    outs:
    - ./data/processed_data.csv

  train_model:
    cmd: python 02c_sklearn_train.py
    deps:
    - 02c_sklearn_train.py
    - ./data/processed_data.csv
    outs:
    - ./images/sklearn_mlp_loss_curve.png
<<<<<<< Updated upstream
=======
    - ./models/sklearn_neuralnet.pkl

  evaluate:
    cmd: python 02d_sklearn_evaluate.py ./models/sklearn_neuralnet.pkl ./data/processed_data.csv
    deps:
    - ./data/processed_data.csv
    - ./models/sklearn_neuralnet.pkl
    - 02d_sklearn_evaluate.py
>>>>>>> Stashed changes
    metrics:
    - scores.json:
        cache: false
    plots:
    - prc.json:
        cache: false
